//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUI.BorderNews {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class BorderNews {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(BorderNews target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::SHPUI.BorderNews.BorderNews @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<head>\r\n    <meta charset=\"utf-8\">\r\n    <title>Заголовок</title>\r\n    <meta nam" +
                        "e=\"description\" content=\"\">\r\n\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"I" +
                        "E=edge\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1" +
                        ", maximum-scale=1\">\r\n\r\n    <link rel=\"stylesheet\" href=\"http://sp-sql/sites/Home" +
                        "/Verstka/css/owl.carousel.min.css\">\r\n    <link rel=\"stylesheet\" href=\"http://sp-" +
                        "sql/sites/Home/Verstka/css/owl.theme.default.min.css\">\r\n\r\n    <link rel=\"stylesh" +
                        "eet\" href=\"http://sp-sql/sites/Home/Verstka/libs/bootstrap/css/bootstrap-grid.mi" +
                        "n.css\">\r\n    <link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400," +
                        "500,700,900&amp;subset=cyrillic,cyrillic-ext\" rel=\"stylesheet\">\r\n    <link rel=\"" +
                        "stylesheet\" href=\"http://sp-sql/sites/Home/Verstka/css/main.css\">\r\n    <link rel" +
                        "=\"stylesheet\" href=\"http://sp-sql/sites/Home/Verstka/css/media.css\">\r\n    <scrip" +
                        "t src=\"http://sp-sql/sites/Home/Verstka/libs/jquery/jquery-1.11.2.min.js\"></scri" +
                        "pt>\r\n    <script src=\"C:\\SharepointTest\\Test\\SHPUI\\Layouts\\SHPUI\\JS\\Ads-admin\\Ad" +
                        "s-Admin.js\"></script>\r\n    <style type=\"text/css\"></style>\r\n    <style type=\"tex" +
                        "t/css\">\r\n        #fancybox-overlay {\r\n            position: fixed;\r\n            " +
                        "top: 0;\r\n            left: 0;\r\n        }\r\n    </style>\r\n    <style type=\"text/cs" +
                        "s\">\r\n        .jcf-unselectable {\r\n            -moz-user-select: none;\r\n         " +
                        "   -webkit-tap-highlight-color: rgba(255,255,255,0);\r\n            -webkit-user-s" +
                        "elect: none;\r\n            user-select: none;\r\n        }\r\n    </style>\r\n</head>\r\n" +
                        "<body>\r\n    <div id=\"wrapper\">\r\n        <div class=\"header\">\r\n            <div c" +
                        "lass=\"container\">\r\n                <div class=\"top-line\">\r\n                    <" +
                        "div class=\"logo\">\r\n                        <a href=\"\">\r\n                        " +
                        "    <img src=\"img/logo.svg\" alt=\"\"></a>\r\n                    </div>\r\n           " +
                        "         <form action=\"\" class=\"search-form\">\r\n                        <input ty" +
                        "pe=\"text\" placeholder=\"Поиск\">\r\n                        <input type=\"submit\" val" +
                        "ue=\"\">\r\n                    </form>\r\n                    <span class=\"ms-siteact" +
                        "ions-root\" id=\"siteactiontd\">\r\n\r\n\r\n                        <span style=\"display:" +
                        " none;\">\r\n                            <menu id=\"zz5_SiteActionsMenuMain\" type=\"S" +
                        "erverMenu\" hideicons=\"true\">\r\n                                <ie:menuitem id=\"z" +
                        "z6_MenuItem_ShareThisSite\" type=\"option\" menugroupid=\"100\" description=\"Посмотре" +
                        "ть, кто здесь находится, и пригласить новых участников.\" text=\"Совместно с...\" o" +
                        "nmenuclick=\"EnsureScriptFunc(\'sharing.js\', \'DisplaySharedWithDialog\', function (" +
                        ") { DisplaySharedWithDialog(\'\\u002fsites\\u002fHome\\u002f\'); })\" enabled=\"true\" c" +
                        "hecked=\"false\" onmenuclick_original=\"EnsureScriptFunc(\'sharing.js\', \'DisplayShar" +
                        "edWithDialog\', function () { DisplaySharedWithDialog(\'\\u002fsites\\u002fHome\\u002" +
                        "f\'); })\" text_original=\"Совместно с...\" description_original=\"Посмотреть, кто зд" +
                        "есь находится, и пригласить новых участников.\" valorig=\"&#10;&#9;\"></ie:menuitem" +
                        ">\r\n                                <ie:menuitem id=\"ctl00_SiteActionsMenuMain_ct" +
                        "l00_MenuItem_EditPage\" type=\"option\" menugroupid=\"200\" description=\"Изменение ко" +
                        "нтента этой страницы.\" text=\"Изменение страницы\" onmenuclick=\"window.location = " +
                        "\'javascript:{EnsureScriptParams(\\\'ribbon\\\', \\\'ChangeWikiPageMode\\\', true);}\';\" i" +
                        "consrc=\"/_layouts/15/images/ActionsEditPage.png?rev=23\" enabled=\"true\" checked=\"" +
                        "false\" onmenuclick_original=\"window.location = \'javascript:{EnsureScriptParams(\\" +
                        "\'ribbon\\\', \\\'ChangeWikiPageMode\\\', true);}\';\" text_original=\"Изменение страницы\"" +
                        " description_original=\"Изменение контента этой страницы.\" valorig=\"&#10;&#9;\"></" +
                        "ie:menuitem>\r\n                                <ie:menuitem id=\"zz7_MenuItem_Crea" +
                        "tePage\" type=\"option\" menugroupid=\"200\" description=\"Создание страницы, которую " +
                        "можно настроить.\" text=\"Добавление страницы\" onmenuclick=\"OpenCreateWebPageDialo" +
                        "g(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u002fcreatewebpage.aspx\')\" iconsr" +
                        "c=\"/_layouts/15/images/NewContentPageHH.png?rev=23\" enabled=\"true\" checked=\"fals" +
                        "e\" onmenuclick_original=\"OpenCreateWebPageDialog(\'\\u002fsites\\u002fHome\\u002f_la" +
                        "youts\\u002f15\\u002fcreatewebpage.aspx\')\" text_original=\"Добавление страницы\" des" +
                        "cription_original=\"Создание страницы, которую можно настроить.\" valorig=\"&#10;&#" +
                        "9;\"></ie:menuitem>\r\n                                <ie:menuitem id=\"zz8_MenuIte" +
                        "m_Create\" type=\"option\" menugroupid=\"200\" description=\"Создание других типов стр" +
                        "аниц, списков, библиотек и сайтов.\" text=\"Добавить приложение\" onmenuclick=\"GoTo" +
                        "Page(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u002faddanapp.aspx\')\" enabled=" +
                        "\"true\" checked=\"false\" onmenuclick_original=\"GoToPage(\'\\u002fsites\\u002fHome\\u00" +
                        "2f_layouts\\u002f15\\u002faddanapp.aspx\')\" text_original=\"Добавить приложение\" des" +
                        "cription_original=\"Создание других типов страниц, списков, библиотек и сайтов.\" " +
                        "valorig=\"&#10;&#9;\"></ie:menuitem>\r\n                                <ie:menuitem" +
                        " id=\"zz9_MenuItem_ViewAllSiteContents\" type=\"option\" menugroupid=\"200\" descripti" +
                        "on=\"Просмотр всех библиотек и списков на данном сайте.\" text=\"Контент сайта\" onm" +
                        "enuclick=\"STSNavigate2(event,\'/sites/Home/_layouts/15/viewlsts.aspx\');\" iconsrc=" +
                        "\"/_layouts/15/images/allcontent32.png?rev=23\" enabled=\"true\" checked=\"false\" onm" +
                        "enuclick_original=\"STSNavigate2(event,\'/sites/Home/_layouts/15/viewlsts.aspx\');\"" +
                        " text_original=\"Контент сайта\" description_original=\"Просмотр всех библиотек и с" +
                        "писков на данном сайте.\" valorig=\"&#10;&#9;\"></ie:menuitem>\r\n                   " +
                        "             <ie:menuitem id=\"zz10_MenuItem_ChangeTheLook\" type=\"option\" menugro" +
                        "upid=\"300\" description=\"Измените внешний вид сайта\" text=\"Изменение оформления\" " +
                        "onmenuclick=\"STSNavigate2(event,\'/sites/Home/_layouts/15/designgallery.aspx\');\" " +
                        "enabled=\"true\" checked=\"false\" onmenuclick_original=\"STSNavigate2(event,\'/sites/" +
                        "Home/_layouts/15/designgallery.aspx\');\" text_original=\"Изменение оформления\" des" +
                        "cription_original=\"Измените внешний вид сайта\" valorig=\"&#10;&#9;\"></ie:menuitem" +
                        ">\r\n                                <ie:menuitem id=\"zz11_MenuItem_Settings\" type" +
                        "=\"option\" menugroupid=\"300\" description=\"Доступ ко всем параметрам этого сайта.\"" +
                        " text=\"Параметры сайта\" onmenuclick=\"GoToPage(\'\\u002fsites\\u002fHome\\u002f_layou" +
                        "ts\\u002f15\\u002fsettings.aspx\')\" iconsrc=\"/_layouts/15/images/settingsIcon.png?r" +
                        "ev=23\" enabled=\"true\" checked=\"false\" onmenuclick_original=\"GoToPage(\'\\u002fsite" +
                        "s\\u002fHome\\u002f_layouts\\u002f15\\u002fsettings.aspx\')\" text_original=\"Параметры" +
                        " сайта\" description_original=\"Доступ ко всем параметрам этого сайта.\" valorig=\"&" +
                        "#10;&#9;\"></ie:menuitem>\r\n                                <ie:menuitem id=\"ctl00" +
                        "_SiteActionsMenuMain_ctl00_ctl02\" type=\"option\" menugroupid=\"2147483647\" descrip" +
                        "tion=\"Начало работы с сайтом.\" text=\"Приступая к работе\" onmenuclick=\"STSNavigat" +
                        "e2(event,\'/sites/Home/GettingStarted.aspx\');\" enabled=\"true\" checked=\"false\" onm" +
                        "enuclick_original=\"STSNavigate2(event,\'/sites/Home/GettingStarted.aspx\');\" text_" +
                        "original=\"Приступая к работе\" description_original=\"Начало работы с сайтом.\" val" +
                        "orig=\"&#10;&#9;\"></ie:menuitem>\r\n                            </menu>\r\n          " +
                        "              </span><span title=\"Параметры\" class=\"ms-siteactions-normal\" id=\"z" +
                        "z12_SiteActionsMenu_t\" onmouseover=\"MMU_PopMenuIfShowing(this);MMU_EcbTableMouse" +
                        "OverOut(this, true)\" onclick=\" CoreInvoke(\'MMU_Open\',byid(\'zz5_SiteActionsMenuMa" +
                        "in\'), MMU_GetMenuFromClientId(\'zz12_SiteActionsMenu\'),event,true, null, 0); retu" +
                        "rn false;\" oncontextmenu=\"ClkElmt(this); return false;\" foa=\"MMU_GetMenuFromClie" +
                        "ntId(\'zz12_SiteActionsMenu\')\" hoverinactive=\"ms-siteactions-normal\" hoveractive=" +
                        "\"ms-siteactions-normal ms-siteactions-hover\"><a title=\"Параметры\" class=\"ms-core" +
                        "-menu-root\" id=\"zz12_SiteActionsMenu\" accesskey=\"/\" onkeydown=\"MMU_EcbLinkOnKeyD" +
                        "own(byid(\'zz5_SiteActionsMenuMain\'), MMU_GetMenuFromClientId(\'zz12_SiteActionsMe" +
                        "nu\'));\" href=\"javascript:;\" serverclientid=\"zz12_SiteActionsMenu\" menutokenvalue" +
                        "s=\"MENUCLIENTID=zz12_SiteActionsMenu,TEMPLATECLIENTID=zz5_SiteActionsMenuMain\"><" +
                        "span class=\"ms-siteactions-imgspan\">\r\n                            <img title=\"Па" +
                        "раметры\" class=\"ms-core-menu-buttonIcon\" alt=\"Параметры\" src=\"/_layouts/15/image" +
                        "s/spcommon.png?rev=23\"></span><span class=\"ms-accessible\">Для открытия меню восп" +
                        "ользуйтесь сочетанием клавиш SHIFT+ВВОД (в новом окне).</span></a></span></span>" +
                        "\r\n\r\n                    <div class=\"lk-box\">\r\n                        <div class" +
                        "=\"img\">\r\n                            <img src=\"http://sp-sql/sites/Home/Verstka/" +
                        "img/face.png\" alt=\"\">\r\n                        </div>\r\n                        <" +
                        "div class=\"tt\">\r\n                            <div class=\"hi\">Здравствуйте</div>\r" +
                        "\n                            <div class=\"name\"><a title=\"Открыть меню\" class=\"ms" +
                        "-core-menu-root\" id=\"zz4_Menu\" accesskey=\"/\" onkeydown=\"MMU_EcbLinkOnKeyDown(byi" +
                        "d(\'zz1_ID_PersonalActionMenu\'), MMU_GetMenuFromClientId(\'zz4_Menu\'), event);\" on" +
                        "click=\" CoreInvoke(\'MMU_Open\',byid(\'zz1_ID_PersonalActionMenu\'), MMU_GetMenuFrom" +
                        "ClientId(\'zz4_Menu\'),event,true, null, 0); return false;\" onfocus=\"MMU_EcbLinkOn" +
                        "FocusBlur(byid(\'zz1_ID_PersonalActionMenu\'), this, true);\" oncontextmenu=\"ClkElm" +
                        "t(this); return false;\" href=\"javascript:;\" serverclientid=\"zz4_Menu\" menutokenv" +
                        "alues=\"MENUCLIENTID=zz4_Menu,TEMPLATECLIENTID=zz1_ID_PersonalActionMenu\">Валенти" +
                        "н Критенко<span class=\"ms-accessible\">Для открытия меню воспользуйтесь сочетание" +
                        "м клавиш SHIFT+ВВОД (в новом окне).</span></a></div>\r\n                        </" +
                        "div>\r\n                        <div class=\"drop-list\">\r\n                         " +
                        "   <ul>\r\n                                <li><a href=\"\">Изменить</a></li>\r\n     " +
                        "                           <li><a href=\"\">Выйти</a></li>\r\n                      " +
                        "      </ul>\r\n                        </div>\r\n                    </div>\r\n       " +
                        "         </div>\r\n                <div class=\"toggle_mnu\">\r\n                    <" +
                        "span class=\"sandwich\">\r\n                        <span class=\"sw-topper\"></span>\r" +
                        "\n                        <span class=\"sw-bottom\"></span>\r\n                      " +
                        "  <span class=\"sw-footer\"></span>\r\n                    </span>\r\n                " +
                        "</div>\r\n                <ul class=\"nav\">\r\n                    <li><a href=\"\">Нов" +
                        "ости</a></li>\r\n                    <li><a href=\"\">Льготы</a></li>\r\n             " +
                        "       <li><a href=\"\">Сервисы и документы</a></li>\r\n                    <li><a h" +
                        "ref=\"\">Карьера</a></li>\r\n                    <li><a href=\"\">Наша жизнь</a></li>\r" +
                        "\n                    <li><a href=\"\">Справочник</a></li>\r\n                    <li" +
                        "><a href=\"\">Компания</a></li>\r\n                </ul>\r\n            </div>\r\n      " +
                        "  </div>\r\n        <div class=\"main bg-white\" id=\"bg-white\">\r\n            <div cl" +
                        "ass=\"toping-box\">\r\n                <div class=\"container\">\r\n                    " +
                        "<ul class=\"pagin\">\r\n                        <li><a href=\"\">Главная</a></li>\r\n   " +
                        "                     <li><a href=\"\">Кредитный департамент</a></li>\r\n            " +
                        "        </ul>\r\n                    <div class=\"title\">Доска объявлений</div>\r\n  " +
                        "                  <form action=\"\" class=\"thanks-from default-form cat-form desk-" +
                        "form\">\r\n                        <div class=\"inp btns-inp\">\r\n                    " +
                        "        <p class=\"label\">Объявления</p>\r\n                            <div class=" +
                        "\"btns\">\r\n                                <a href=\"\" class=\"btn\">Активные</a>\r\n  " +
                        "                              <a href=\"\" class=\"btn\">На модерации</a>\r\n         " +
                        "                   </div>\r\n                        </div>\r\n                     " +
                        "   <div class=\"inp select-inp\">\r\n                            <p class=\"label\">Ка" +
                        "тегории</p>\r\n                            <select class=\"jcf-hidden\">\r\n          " +
                        "                      <option value=\"\">Любая</option>\r\n                         " +
                        "       <option value=\"\">Любая</option>\r\n                            </select>\r\n\r" +
                        "\n                        </div>\r\n                        <div class=\"ch\">\r\n     " +
                        "                       <div class=\"chk-area chk-unchecked\"><span></span></div>\r\n" +
                        "                            <input type=\"checkbox\" id=\"c1\" class=\"jcf-hidden\">\r\n" +
                        "                            <label for=\"c1\">Мои объявления</label>\r\n            " +
                        "            </div>\r\n                        <input class=\"btn\" type=\"submit\" val" +
                        "ue=\"+ Добавить объявлени\">\r\n                    </form>\r\n                </div>\r" +
                        "\n            </div>\r\n            \r\n            \r\n        </div>\r\n        <div cl" +
                        "ass=\"footer footer-inner\">\r\n            <div class=\"container\">\r\n               " +
                        " <div class=\"row\">\r\n                    <div class=\"col-sm-12\">\r\n               " +
                        "         <div class=\"wrap\">\r\n                            <div class=\"copy\">© 201" +
                        "8 РН Банк. Корпоративный портал сотрудников банка.</div>\r\n                      " +
                        "  </div>\r\n                    </div>\r\n                </div>\r\n            </div>" +
                        "\r\n        </div>\r\n    </div>\r\n\r\n\r\n    <!--[if lt IE 9]>\r\n\t<script src=\"libs/html" +
                        "5shiv/es5-shim.min.js\"></script>\r\n\t<script src=\"libs/html5shiv/html5shiv.min.js\"" +
                        "></script>\r\n\t<script src=\"libs/html5shiv/html5shiv-printshiv.min.js\"></script>\r\n" +
                        "\t<script src=\"libs/respond/respond.min.js\"></script>\r\n\t<![endifmain bg-white\r\n\r\n" +
                        "    <script src=\"http://sp-sql/sites/Home/Verstka/libs/jquery/jquery-1.11.2.min." +
                        "js\"></script>\r\n    <script src=\"http://sp-sql/sites/Home/Verstka/libs/plugins-sc" +
                        "roll/plugins-scroll.js\"></script>\r\n    <script src=\"http://sp-sql/sites/Home/Ver" +
                        "stka/js/owl.carousel.js\"></script>\r\n    <script src=\"http://sp-sql/sites/Home/Ve" +
                        "rstka/js/jcf.js\"></script>\r\n    <script src=\"http://sp-sql/sites/Home/Verstka/js" +
                        "/jcf.checkbox.js\"></script>\r\n    <script src=\"http://sp-sql/sites/Home/Verstka/j" +
                        "s/jcf.radio.js\"></script>\r\n    <script src=\"http://sp-sql/sites/Home/Verstka/js/" +
                        "common.js\"></script>\r\n\r\n\r\n    <div id=\"fancybox-tmp\"></div>\r\n    <div id=\"fancyb" +
                        "ox-loading\">\r\n        <div></div>\r\n    </div>\r\n    <div id=\"fancybox-overlay\"></" +
                        "div>\r\n    <div id=\"fancybox-wrap\">\r\n        <div id=\"fancybox-outer\">\r\n         " +
                        "   <div class=\"fancybox-bg\" id=\"fancybox-bg-n\"></div>\r\n            <div class=\"f" +
                        "ancybox-bg\" id=\"fancybox-bg-ne\"></div>\r\n            <div class=\"fancybox-bg\" id=" +
                        "\"fancybox-bg-e\"></div>\r\n            <div class=\"fancybox-bg\" id=\"fancybox-bg-se\"" +
                        "></div>\r\n            <div class=\"fancybox-bg\" id=\"fancybox-bg-s\"></div>\r\n       " +
                        "     <div class=\"fancybox-bg\" id=\"fancybox-bg-sw\"></div>\r\n            <div class" +
                        "=\"fancybox-bg\" id=\"fancybox-bg-w\"></div>\r\n            <div class=\"fancybox-bg\" i" +
                        "d=\"fancybox-bg-nw\"></div>\r\n            <div id=\"fancybox-content\"></div>\r\n      " +
                        "      <a id=\"fancybox-close\"></a>\r\n            <div id=\"fancybox-title\"></div>\r\n" +
                        "            <a href=\"javascript:;\" id=\"fancybox-left\"><span class=\"fancy-ico\" id" +
                        "=\"fancybox-left-ico\"></span></a><a href=\"javascript:;\" id=\"fancybox-right\"><span" +
                        " class=\"fancy-ico\" id=\"fancybox-right-ico\"></span></a>\r\n        </div>\r\n    </di" +
                        "v>\r\n</body>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
