//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUI.CreateEditBoardingNews {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class CreateEditBoardingNews {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(CreateEditBoardingNews target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::SHPUI.CreateEditBoardingNews.CreateEditBoardingNews @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html class=\"ie ie6\" lang=\"en\"> <![endif]-->" +
                        "\r\n<!--[if IE 7 ]><html class=\"ie ie7\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 8 ]><h" +
                        "tml class=\"ie ie8\" lang=\"en\"> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!-->\r\n<ht" +
                        "ml lang=\"ru\">\r\n<!--<![endif]-->\r\n\r\n<head>\r\n    <meta charset=\"utf-8\">\r\n    <titl" +
                        "e>Заголовок</title>\r\n    <meta name=\"description\" content=\"\">\r\n\r\n    <meta http-" +
                        "equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n    <meta name=\"viewport\" content=\"w" +
                        "idth=device-width, initial-scale=1, maximum-scale=1\">\r\n\r\n    <link rel=\"styleshe" +
                        "et\" href=\"http://sp-sql/sites/Home/Verstka/css/owl.carousel.min.css\">\r\n    <link" +
                        " rel=\"stylesheet\" href=\"http://sp-sql/sites/Home/Verstka/css/owl.theme.default.m" +
                        "in.css\">\r\n\r\n    <link rel=\"stylesheet\" href=\"http://sp-sql/sites/Home/Verstka/li" +
                        "bs/bootstrap/css/bootstrap-grid.min.css\">\r\n    <link href=\"https://fonts.googlea" +
                        "pis.com/css?family=Roboto:300,400,500,700,900&amp;subset=cyrillic,cyrillic-ext\" " +
                        "rel=\"stylesheet\">\r\n    <link rel=\"stylesheet\" href=\"http://sp-sql/sites/Home/Ver" +
                        "stka/css/main.css\">\r\n    <link rel=\"stylesheet\" href=\"http://sp-sql/sites/Home/V" +
                        "erstka/css/media.css\">\r\n    <script src=\"http://sp-sql/sites/Home/Verstka/libs/j" +
                        "query/jquery-1.11.2.min.js\"></script>    \r\n    <script src=\"C:\\SharepointTest\\Te" +
                        "st\\SHPUI\\Layouts\\SHPUI\\JS\\EditBilboard\\RightPanel\\BoardingModeration.js\"></scrip" +
                        "t>\r\n</head>\r\n\r\n<body>\r\n    <div id=\"wrapper\">\r\n        <div class=\"header\">\r\n   " +
                        "         <div class=\"container\">\r\n                <div class=\"top-line\">\r\n      " +
                        "              <div class=\"logo\"><a href=\"\">\r\n                        <img src=\"i" +
                        "mg/logo.svg\" alt=\"\"></a></div>\r\n                    <form action=\"\" class=\"searc" +
                        "h-form\">\r\n                        <input type=\"text\" placeholder=\"Поиск\">\r\n     " +
                        "                   <input type=\"submit\" value=\"\">\r\n                    </form>\r\n" +
                        "                    <div id=\"suiteBarButtons\">\r\n\t\t\t\t\t   <span class=\"ms-siteacti" +
                        "ons-root\" id=\"siteactiontd\">\r\n\t\t\t\t\t   \r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<span style=\"display: none" +
                        ";\"><menu id=\"zz5_SiteActionsMenuMain\" type=\"ServerMenu\" hideicons=\"true\"><ie:men" +
                        "uitem id=\"zz6_MenuItem_ShareThisSite\" type=\"option\" menugroupid=\"100\" descriptio" +
                        "n=\"Посмотреть, кто здесь находится, и пригласить новых участников.\" text=\"Совмес" +
                        "тно с...\" onmenuclick=\"EnsureScriptFunc(\'sharing.js\', \'DisplaySharedWithDialog\'," +
                        " function () { DisplaySharedWithDialog(\'\\u002fsites\\u002fHome\\u002f\'); })\" check" +
                        "ed=\"false\" enabled=\"true\" onMenuClick_Original=\"EnsureScriptFunc(\'sharing.js\', \'" +
                        "DisplaySharedWithDialog\', function () { DisplaySharedWithDialog(\'\\u002fsites\\u00" +
                        "2fHome\\u002f\'); })\" text_Original=\"Совместно с...\" description_Original=\"Посмотр" +
                        "еть, кто здесь находится, и пригласить новых участников.\" valOrig=\"&#10;&#9;\"></" +
                        "ie:menuitem>\r\n\t<ie:menuitem id=\"ctl00_SiteActionsMenuMain_ctl00_MenuItem_EditPag" +
                        "e\" type=\"option\" menugroupid=\"200\" description=\"Изменение контента этой страницы" +
                        ".\" text=\"Изменение страницы\" onmenuclick=\"window.location = \'javascript:{EnsureS" +
                        "criptParams(\\\'ribbon\\\', \\\'ChangeWikiPageMode\\\', true);}\';\" iconsrc=\"/_layouts/15" +
                        "/images/ActionsEditPage.png?rev=23\" checked=\"false\" enabled=\"true\" onMenuClick_O" +
                        "riginal=\"window.location = \'javascript:{EnsureScriptParams(\\\'ribbon\\\', \\\'ChangeW" +
                        "ikiPageMode\\\', true);}\';\" text_Original=\"Изменение страницы\" description_Origina" +
                        "l=\"Изменение контента этой страницы.\" valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:m" +
                        "enuitem id=\"zz7_MenuItem_CreatePage\" type=\"option\" menugroupid=\"200\" description" +
                        "=\"Создание страницы, которую можно настроить.\" text=\"Добавление страницы\" onmenu" +
                        "click=\"OpenCreateWebPageDialog(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u002" +
                        "fcreatewebpage.aspx\')\" iconsrc=\"/_layouts/15/images/NewContentPageHH.png?rev=23\"" +
                        " checked=\"false\" enabled=\"true\" onMenuClick_Original=\"OpenCreateWebPageDialog(\'\\" +
                        "u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u002fcreatewebpage.aspx\')\" text_Origi" +
                        "nal=\"Добавление страницы\" description_Original=\"Создание страницы, которую можно" +
                        " настроить.\" valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz8_MenuItem_" +
                        "Create\" type=\"option\" menugroupid=\"200\" description=\"Создание других типов стран" +
                        "иц, списков, библиотек и сайтов.\" text=\"Добавить приложение\" onmenuclick=\"GoToPa" +
                        "ge(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u002faddanapp.aspx\')\" checked=\"f" +
                        "alse\" enabled=\"true\" onMenuClick_Original=\"GoToPage(\'\\u002fsites\\u002fHome\\u002f" +
                        "_layouts\\u002f15\\u002faddanapp.aspx\')\" text_Original=\"Добавить приложение\" descr" +
                        "iption_Original=\"Создание других типов страниц, списков, библиотек и сайтов.\" va" +
                        "lOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz9_MenuItem_ViewAllSiteCont" +
                        "ents\" type=\"option\" menugroupid=\"200\" description=\"Просмотр всех библиотек и спи" +
                        "сков на данном сайте.\" text=\"Контент сайта\" onmenuclick=\"STSNavigate2(event,\'/si" +
                        "tes/Home/_layouts/15/viewlsts.aspx\');\" iconsrc=\"/_layouts/15/images/allcontent32" +
                        ".png?rev=23\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"STSNavigate2(e" +
                        "vent,\'/sites/Home/_layouts/15/viewlsts.aspx\');\" text_Original=\"Контент сайта\" de" +
                        "scription_Original=\"Просмотр всех библиотек и списков на данном сайте.\" valOrig=" +
                        "\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz10_MenuItem_ChangeTheLook\" type=" +
                        "\"option\" menugroupid=\"300\" description=\"Измените внешний вид сайта\" text=\"Измене" +
                        "ние оформления\" onmenuclick=\"STSNavigate2(event,\'/sites/Home/_layouts/15/designg" +
                        "allery.aspx\');\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"STSNavigate" +
                        "2(event,\'/sites/Home/_layouts/15/designgallery.aspx\');\" text_Original=\"Изменение" +
                        " оформления\" description_Original=\"Измените внешний вид сайта\" valOrig=\"&#10;&#9" +
                        ";\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz11_MenuItem_Settings\" type=\"option\" menug" +
                        "roupid=\"300\" description=\"Доступ ко всем параметрам этого сайта.\" text=\"Параметр" +
                        "ы сайта\" onmenuclick=\"GoToPage(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u002" +
                        "fsettings.aspx\')\" iconsrc=\"/_layouts/15/images/settingsIcon.png?rev=23\" checked=" +
                        "\"false\" enabled=\"true\" onMenuClick_Original=\"GoToPage(\'\\u002fsites\\u002fHome\\u00" +
                        "2f_layouts\\u002f15\\u002fsettings.aspx\')\" text_Original=\"Параметры сайта\" descrip" +
                        "tion_Original=\"Доступ ко всем параметрам этого сайта.\" valOrig=\"&#10;&#9;\"></ie:" +
                        "menuitem>\r\n\t<ie:menuitem id=\"ctl00_SiteActionsMenuMain_ctl00_ctl02\" type=\"option" +
                        "\" menugroupid=\"2147483647\" description=\"Начало работы с сайтом.\" text=\"Приступая" +
                        " к работе\" onmenuclick=\"STSNavigate2(event,\'/sites/Home/GettingStarted.aspx\');\" " +
                        "checked=\"false\" enabled=\"true\" onMenuClick_Original=\"STSNavigate2(event,\'/sites/" +
                        "Home/GettingStarted.aspx\');\" text_Original=\"Приступая к работе\" description_Orig" +
                        "inal=\"Начало работы с сайтом.\" valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t</menu></spa" +
                        "n><span title=\"Параметры\" class=\"ms-siteactions-normal\" id=\"zz12_SiteActionsMenu" +
                        "_t\" onmouseover=\"MMU_PopMenuIfShowing(this);MMU_EcbTableMouseOverOut(this, true)" +
                        "\" onclick=\" CoreInvoke(\'MMU_Open\',byid(\'zz5_SiteActionsMenuMain\'), MMU_GetMenuFr" +
                        "omClientId(\'zz12_SiteActionsMenu\'),event,true, null, 0); return false;\" oncontex" +
                        "tmenu=\"ClkElmt(this); return false;\" foa=\"MMU_GetMenuFromClientId(\'zz12_SiteActi" +
                        "onsMenu\')\" hoverinactive=\"ms-siteactions-normal\" hoveractive=\"ms-siteactions-nor" +
                        "mal ms-siteactions-hover\"><a title=\"Параметры\" class=\"ms-core-menu-root\" id=\"zz1" +
                        "2_SiteActionsMenu\" accesskey=\"/\" onkeydown=\"MMU_EcbLinkOnKeyDown(byid(\'zz5_SiteA" +
                        "ctionsMenuMain\'), MMU_GetMenuFromClientId(\'zz12_SiteActionsMenu\'));\" href=\"javas" +
                        "cript:;\" serverclientid=\"zz12_SiteActionsMenu\" menutokenvalues=\"MENUCLIENTID=zz1" +
                        "2_SiteActionsMenu,TEMPLATECLIENTID=zz5_SiteActionsMenuMain\"><span class=\"ms-site" +
                        "actions-imgspan\"><img title=\"Параметры\" class=\"ms-core-menu-buttonIcon\" alt=\"Пар" +
                        "аметры\" src=\"/_layouts/15/images/spcommon.png?rev=23\"></span><span class=\"ms-acc" +
                        "essible\">Для открытия меню воспользуйтесь сочетанием клавиш SHIFT+ВВОД (в новом " +
                        "окне).</span></a></span></span>\r\n<span id=\"ms-help\">\r\n\t<a title=\"Справка\" id=\"ct" +
                        "l00_TopHelpLink\" accesskey=\"6\" style=\"width: 30px; height: 30px; display: inline" +
                        "-block;\" onmouseover=\"this.firstChild.firstChild.firstChild.style.left=\'-1px\'; t" +
                        "his.firstChild.firstChild.firstChild.style.top=\'-1px\';\" onmouseout=\"this.firstCh" +
                        "ild.firstChild.firstChild.style.left=\'-19px\'; this.firstChild.firstChild.firstCh" +
                        "ild.style.top=\'-1px\';\" onclick=\"TopHelpButtonClick(\'HelpHome\',event);return fals" +
                        "e\" href=\"../_catalogs/masterpage/#\"><span style=\"padding: 7px; width: 16px; heig" +
                        "ht: 16px; overflow: hidden; display: inline-block;\"><span class=\"s4-clust\" style" +
                        "=\"width: 16px; height: 16px; overflow: hidden; display: inline-block; position: " +
                        "relative;\"><img style=\"border: 0px currentColor; left: -19px; top: -1px; positio" +
                        "n: absolute;\" alt=\"Справка\" src=\"/_layouts/15/1049/images/spintl.png?rev=23\"></s" +
                        "pan></span></a>\r\n</span>\r\n\t\t\t\t</div>\r\n                    <div class=\"lk-box\">\r\n" +
                        "                        <div class=\"img\">\r\n                            <img src=" +
                        "\"img/face.png\" alt=\"\"></div>\r\n                        <div class=\"tt\">\r\n        " +
                        "                    <div class=\"hi\">Здравствуйте</div>\r\n                        " +
                        "    <div class=\"name\"><a title=\"Открыть меню\" class=\"ms-core-menu-root\" id=\"zz4_" +
                        "Menu\" accesskey=\"/\" onkeydown=\"MMU_EcbLinkOnKeyDown(byid(\'zz1_ID_PersonalActionM" +
                        "enu\'), MMU_GetMenuFromClientId(\'zz4_Menu\'), event);\" onclick=\" CoreInvoke(\'MMU_O" +
                        "pen\',byid(\'zz1_ID_PersonalActionMenu\'), MMU_GetMenuFromClientId(\'zz4_Menu\'),even" +
                        "t,true, null, 0); return false;\" onfocus=\"MMU_EcbLinkOnFocusBlur(byid(\'zz1_ID_Pe" +
                        "rsonalActionMenu\'), this, true);\" oncontextmenu=\"ClkElmt(this); return false;\" h" +
                        "ref=\"javascript:;\" serverclientid=\"zz4_Menu\" menutokenvalues=\"MENUCLIENTID=zz4_M" +
                        "enu,TEMPLATECLIENTID=zz1_ID_PersonalActionMenu\">Валентин Критенко<span class=\"ms" +
                        "-accessible\">Для открытия меню воспользуйтесь сочетанием клавиш SHIFT+ВВОД (в но" +
                        "вом окне).</span></a></div>\r\n                        \r\n                        <" +
                        "/div>\r\n                        <div class=\"drop-list\">\r\n                        " +
                        "    <ul>\r\n                                <li><a href=\"\">Изменить</a></li>\r\n    " +
                        "                            <li><a href=\"\">Выйти</a></li>\r\n                     " +
                        "       </ul>\r\n                        </div>\r\n                    </div>\r\n      " +
                        "          </div>\r\n                <div class=\"toggle_mnu\">\r\n                    " +
                        "<span class=\"sandwich\">\r\n                        <span class=\"sw-topper\"></span>" +
                        "\r\n                        <span class=\"sw-bottom\"></span>\r\n                     " +
                        "   <span class=\"sw-footer\"></span>\r\n                    </span>\r\n               " +
                        " </div>\r\n                <ul class=\"nav\">\r\n                    <li><a href=\"\">Но" +
                        "вости</a></li>\r\n                    <li><a href=\"\">Льготы</a></li>\r\n            " +
                        "        <li><a href=\"\">Сервисы и документы</a></li>\r\n                    <li><a " +
                        "href=\"\">Карьера</a></li>\r\n                    <li><a href=\"\">Наша жизнь</a></li>" +
                        "\r\n                    <li><a href=\"\">Справочник</a></li>\r\n                    <l" +
                        "i><a href=\"\">Компания</a></li>\r\n                </ul>\r\n            </div>\r\n     " +
                        "   </div>\r\n        <div class=\"main bg-white\">\r\n            <div class=\"toping-b" +
                        "ox\">\r\n                <div class=\"container\">\r\n                    <ul class=\"pa" +
                        "gin\">\r\n                        <li><a href=\"\">Главная</a></li>\r\n                " +
                        "    </ul>\r\n                    <div class=\"title\">Редактирование объявления</div" +
                        ">\r\n                </div>\r\n            </div>\r\n            <div class=\"container" +
                        "\">\r\n                <div class=\"two-columns\">\r\n                    <div class=\"r" +
                        "ow\" id =\"RightPanel\">\r\n                        <div class=\"col-md-9 col-sm-12\">\r" +
                        "\n                            <div class=\"content-box\">\r\n\r\n                      " +
                        "          <div class=\"section-padding\">\r\n                                    <fo" +
                        "rm action=\"\" class=\"default-form edit-form\">\r\n                                  " +
                        "      <div class=\"row-inp\">\r\n                                            <p clas" +
                        "s=\"label\">Заголовок</p>\r\n                                            <input type" +
                        "=\"text\">\r\n                                        </div>\r\n                      " +
                        "                  <div class=\"row-inp\">\r\n                                       " +
                        "     <p class=\"label\">Категории</p>\r\n                                           " +
                        " <select class=\"cat-select\">\r\n                                                <o" +
                        "ption value=\"\"></option>\r\n                                                <optio" +
                        "n value=\"\">Категории</option>\r\n                                            </sel" +
                        "ect>\r\n                                        </div>\r\n                          " +
                        "              <div class=\"row-inp\">\r\n                                           " +
                        " <p class=\"label\">Описание</p>\r\n                                            <tex" +
                        "tarea></textarea>\r\n                                        </div>\r\n             " +
                        "                           <div class=\"row-inp\">\r\n                              " +
                        "              <p class=\"label\">Фотографии, не более 3</p>\r\n                     " +
                        "                       <div class=\"file\">\r\n                                     " +
                        "           <input id=\"file4\" type=\"file\" title=\"Загрузите фото\" />\r\n            " +
                        "                                    <span class=\"file-input-text\">name.png</span" +
                        ">\r\n                                            </div>\r\n                         " +
                        "               </div>\r\n                                        <div class=\"row-i" +
                        "np\">\r\n                                            <p class=\"label\">Объявление бу" +
                        "дет отправлено на модерацию</p>\r\n                                            <in" +
                        "put type=\"submit\" class=\"btn\" value=\"Сохранить\">\r\n                              " +
                        "          </div>\r\n                                    </form>\r\n                 " +
                        "               </div>\r\n\r\n                            </div>\r\n                   " +
                        "     </div>\r\n                    </div>\r\n                </div>\r\n            </d" +
                        "iv>\r\n        </div>\r\n        <div class=\"footer footer-inner\">\r\n            <div" +
                        " class=\"container\">\r\n                <div class=\"row\">\r\n                    <div" +
                        " class=\"col-sm-12\">\r\n                        <div class=\"wrap\">\r\n               " +
                        "             <div class=\"copy\">© 2018 РН Банк. Корпоративный портал сотрудников " +
                        "банка.</div>\r\n                        </div>\r\n                    </div>\r\n      " +
                        "          </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n\r\n    <!--[i" +
                        "f lt IE 9]>\r\n\t<script src=\"libs/html5shiv/es5-shim.min.js\"></script>\r\n\t<script s" +
                        "rc=\"libs/html5shiv/html5shiv.min.js\"></script>\r\n\t<script src=\"libs/html5shiv/htm" +
                        "l5shiv-printshiv.min.js\"></script>\r\n\t<script src=\"libs/respond/respond.min.js\"><" +
                        "/script>\r\n\t<![endif]-->\r\n\r\n    <script src=\"http://sp-sql/sites/Home/Verstka/lib" +
                        "s/jquery/jquery-1.11.2.min.js\"></script>\r\n    <script src=\"http://sp-sql/sites/H" +
                        "ome/Verstka/libs/plugins-scroll/plugins-scroll.js\"></script>\r\n    <script src=\"h" +
                        "ttp://sp-sql/sites/Home/Verstka/js/owl.carousel.js\"></script>\r\n    <script src=\"" +
                        "http://sp-sql/sites/Home/Verstka/js/jcf.js\"></script>\r\n    <script src=\"http://s" +
                        "p-sql/sites/Home/Verstka/js/jcf.checkbox.js\"></script>\r\n    <script src=\"http://" +
                        "sp-sql/sites/Home/Verstka/js/jcf.radio.js\"></script>\r\n    <script src=\"http://sp" +
                        "-sql/sites/Home/Verstka/js/common.js\"></script>\r\n\r\n</body>\r\n</html>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
