//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUI.CreateEditBoardingNews {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class CreateEditBoardingNews {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(CreateEditBoardingNews target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::SHPUI.CreateEditBoardingNews.CreateEditBoardingNews @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html class=\"ie ie6\" lang=\"en\"> <![endif]-->" +
                        "\r\n<!--[if IE 7 ]><html class=\"ie ie7\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 8 ]><h" +
                        "tml class=\"ie ie8\" lang=\"en\"> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!-->\r\n<ht" +
                        "ml lang=\"ru\">\r\n<!--<![endif]-->\r\n\r\n<head>\r\n    <meta charset=\"utf-8\">\r\n    <titl" +
                        "e>Заголовок</title>\r\n    <meta name=\"description\" content=\"\">\r\n\r\n    <meta http-" +
                        "equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n    <meta name=\"viewport\" content=\"w" +
                        "idth=device-width, initial-scale=1, maximum-scale=1\">\r\n\r\n    <link rel=\"styleshe" +
                        "et\" href=\"http://sp-sql/sites/Home/Verstka/css/owl.carousel.min.css\">\r\n    <link" +
                        " rel=\"stylesheet\" href=\"http://sp-sql/sites/Home/Verstka/css/owl.theme.default.m" +
                        "in.css\">\r\n\r\n    <link rel=\"stylesheet\" href=\"http://sp-sql/sites/Home/Verstka/li" +
                        "bs/bootstrap/css/bootstrap-grid.min.css\">\r\n    <link href=\"https://fonts.googlea" +
                        "pis.com/css?family=Roboto:300,400,500,700,900&amp;subset=cyrillic,cyrillic-ext\" " +
                        "rel=\"stylesheet\">\r\n    <link rel=\"stylesheet\" href=\"http://sp-sql/sites/Home/Ver" +
                        "stka/css/main.css\">\r\n    <link rel=\"stylesheet\" href=\"http://sp-sql/sites/Home/V" +
                        "erstka/css/media.css\">\r\n</head>\r\n\r\n<body>\r\n    <div id=\"wrapper\">\r\n        <div " +
                        "class=\"header\">\r\n            <div class=\"container\">\r\n                <div class" +
                        "=\"top-line\">\r\n                    <div class=\"logo\"><a href=\"\">\r\n               " +
                        "         <img src=\"img/logo.svg\" alt=\"\"></a></div>\r\n                    <form ac" +
                        "tion=\"\" class=\"search-form\">\r\n                        <input type=\"text\" placeho" +
                        "lder=\"Поиск\">\r\n                        <input type=\"submit\" value=\"\">\r\n         " +
                        "           </form>\r\n                    <div id=\"suiteBarButtons\">\r\n\t\t\t\t\t   <spa" +
                        "n class=\"ms-siteactions-root\" id=\"siteactiontd\">\r\n\t\t\t\t\t   \r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<span " +
                        "style=\"display: none;\"><menu id=\"zz5_SiteActionsMenuMain\" type=\"ServerMenu\" hide" +
                        "icons=\"true\"><ie:menuitem id=\"zz6_MenuItem_ShareThisSite\" type=\"option\" menugrou" +
                        "pid=\"100\" description=\"Посмотреть, кто здесь находится, и пригласить новых участ" +
                        "ников.\" text=\"Совместно с...\" onmenuclick=\"EnsureScriptFunc(\'sharing.js\', \'Displ" +
                        "aySharedWithDialog\', function () { DisplaySharedWithDialog(\'\\u002fsites\\u002fHom" +
                        "e\\u002f\'); })\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"EnsureScript" +
                        "Func(\'sharing.js\', \'DisplaySharedWithDialog\', function () { DisplaySharedWithDia" +
                        "log(\'\\u002fsites\\u002fHome\\u002f\'); })\" text_Original=\"Совместно с...\" descripti" +
                        "on_Original=\"Посмотреть, кто здесь находится, и пригласить новых участников.\" va" +
                        "lOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"ctl00_SiteActionsMenuMain_ct" +
                        "l00_MenuItem_EditPage\" type=\"option\" menugroupid=\"200\" description=\"Изменение ко" +
                        "нтента этой страницы.\" text=\"Изменение страницы\" onmenuclick=\"window.location = " +
                        "\'javascript:{EnsureScriptParams(\\\'ribbon\\\', \\\'ChangeWikiPageMode\\\', true);}\';\" i" +
                        "consrc=\"/_layouts/15/images/ActionsEditPage.png?rev=23\" checked=\"false\" enabled=" +
                        "\"true\" onMenuClick_Original=\"window.location = \'javascript:{EnsureScriptParams(\\" +
                        "\'ribbon\\\', \\\'ChangeWikiPageMode\\\', true);}\';\" text_Original=\"Изменение страницы\"" +
                        " description_Original=\"Изменение контента этой страницы.\" valOrig=\"&#10;&#9;\"></" +
                        "ie:menuitem>\r\n\t<ie:menuitem id=\"zz7_MenuItem_CreatePage\" type=\"option\" menugroup" +
                        "id=\"200\" description=\"Создание страницы, которую можно настроить.\" text=\"Добавле" +
                        "ние страницы\" onmenuclick=\"OpenCreateWebPageDialog(\'\\u002fsites\\u002fHome\\u002f_" +
                        "layouts\\u002f15\\u002fcreatewebpage.aspx\')\" iconsrc=\"/_layouts/15/images/NewConte" +
                        "ntPageHH.png?rev=23\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"OpenCr" +
                        "eateWebPageDialog(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u002fcreatewebpag" +
                        "e.aspx\')\" text_Original=\"Добавление страницы\" description_Original=\"Создание стр" +
                        "аницы, которую можно настроить.\" valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuit" +
                        "em id=\"zz8_MenuItem_Create\" type=\"option\" menugroupid=\"200\" description=\"Создани" +
                        "е других типов страниц, списков, библиотек и сайтов.\" text=\"Добавить приложение\"" +
                        " onmenuclick=\"GoToPage(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u002faddanap" +
                        "p.aspx\')\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"GoToPage(\'\\u002fs" +
                        "ites\\u002fHome\\u002f_layouts\\u002f15\\u002faddanapp.aspx\')\" text_Original=\"Добави" +
                        "ть приложение\" description_Original=\"Создание других типов страниц, списков, биб" +
                        "лиотек и сайтов.\" valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz9_Menu" +
                        "Item_ViewAllSiteContents\" type=\"option\" menugroupid=\"200\" description=\"Просмотр " +
                        "всех библиотек и списков на данном сайте.\" text=\"Контент сайта\" onmenuclick=\"STS" +
                        "Navigate2(event,\'/sites/Home/_layouts/15/viewlsts.aspx\');\" iconsrc=\"/_layouts/15" +
                        "/images/allcontent32.png?rev=23\" checked=\"false\" enabled=\"true\" onMenuClick_Orig" +
                        "inal=\"STSNavigate2(event,\'/sites/Home/_layouts/15/viewlsts.aspx\');\" text_Origina" +
                        "l=\"Контент сайта\" description_Original=\"Просмотр всех библиотек и списков на дан" +
                        "ном сайте.\" valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz10_MenuItem_" +
                        "ChangeTheLook\" type=\"option\" menugroupid=\"300\" description=\"Измените внешний вид" +
                        " сайта\" text=\"Изменение оформления\" onmenuclick=\"STSNavigate2(event,\'/sites/Home" +
                        "/_layouts/15/designgallery.aspx\');\" checked=\"false\" enabled=\"true\" onMenuClick_O" +
                        "riginal=\"STSNavigate2(event,\'/sites/Home/_layouts/15/designgallery.aspx\');\" text" +
                        "_Original=\"Изменение оформления\" description_Original=\"Измените внешний вид сайт" +
                        "а\" valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz11_MenuItem_Settings\"" +
                        " type=\"option\" menugroupid=\"300\" description=\"Доступ ко всем параметрам этого са" +
                        "йта.\" text=\"Параметры сайта\" onmenuclick=\"GoToPage(\'\\u002fsites\\u002fHome\\u002f_" +
                        "layouts\\u002f15\\u002fsettings.aspx\')\" iconsrc=\"/_layouts/15/images/settingsIcon." +
                        "png?rev=23\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"GoToPage(\'\\u002" +
                        "fsites\\u002fHome\\u002f_layouts\\u002f15\\u002fsettings.aspx\')\" text_Original=\"Пара" +
                        "метры сайта\" description_Original=\"Доступ ко всем параметрам этого сайта.\" valOr" +
                        "ig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"ctl00_SiteActionsMenuMain_ctl00" +
                        "_ctl02\" type=\"option\" menugroupid=\"2147483647\" description=\"Начало работы с сайт" +
                        "ом.\" text=\"Приступая к работе\" onmenuclick=\"STSNavigate2(event,\'/sites/Home/Gett" +
                        "ingStarted.aspx\');\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"STSNavi" +
                        "gate2(event,\'/sites/Home/GettingStarted.aspx\');\" text_Original=\"Приступая к рабо" +
                        "те\" description_Original=\"Начало работы с сайтом.\" valOrig=\"&#10;&#9;\"></ie:menu" +
                        "item>\r\n\t</menu></span><span title=\"Параметры\" class=\"ms-siteactions-normal\" id=\"" +
                        "zz12_SiteActionsMenu_t\" onmouseover=\"MMU_PopMenuIfShowing(this);MMU_EcbTableMous" +
                        "eOverOut(this, true)\" onclick=\" CoreInvoke(\'MMU_Open\',byid(\'zz5_SiteActionsMenuM" +
                        "ain\'), MMU_GetMenuFromClientId(\'zz12_SiteActionsMenu\'),event,true, null, 0); ret" +
                        "urn false;\" oncontextmenu=\"ClkElmt(this); return false;\" foa=\"MMU_GetMenuFromCli" +
                        "entId(\'zz12_SiteActionsMenu\')\" hoverinactive=\"ms-siteactions-normal\" hoveractive" +
                        "=\"ms-siteactions-normal ms-siteactions-hover\"><a title=\"Параметры\" class=\"ms-cor" +
                        "e-menu-root\" id=\"zz12_SiteActionsMenu\" accesskey=\"/\" onkeydown=\"MMU_EcbLinkOnKey" +
                        "Down(byid(\'zz5_SiteActionsMenuMain\'), MMU_GetMenuFromClientId(\'zz12_SiteActionsM" +
                        "enu\'));\" href=\"javascript:;\" serverclientid=\"zz12_SiteActionsMenu\" menutokenvalu" +
                        "es=\"MENUCLIENTID=zz12_SiteActionsMenu,TEMPLATECLIENTID=zz5_SiteActionsMenuMain\">" +
                        "<span class=\"ms-siteactions-imgspan\"><img title=\"Параметры\" class=\"ms-core-menu-" +
                        "buttonIcon\" alt=\"Параметры\" src=\"/_layouts/15/images/spcommon.png?rev=23\"></span" +
                        "><span class=\"ms-accessible\">Для открытия меню воспользуйтесь сочетанием клавиш " +
                        "SHIFT+ВВОД (в новом окне).</span></a></span></span>\r\n<span id=\"ms-help\">\r\n\t<a ti" +
                        "tle=\"Справка\" id=\"ctl00_TopHelpLink\" accesskey=\"6\" style=\"width: 30px; height: 3" +
                        "0px; display: inline-block;\" onmouseover=\"this.firstChild.firstChild.firstChild." +
                        "style.left=\'-1px\'; this.firstChild.firstChild.firstChild.style.top=\'-1px\';\" onmo" +
                        "useout=\"this.firstChild.firstChild.firstChild.style.left=\'-19px\'; this.firstChil" +
                        "d.firstChild.firstChild.style.top=\'-1px\';\" onclick=\"TopHelpButtonClick(\'HelpHome" +
                        "\',event);return false\" href=\"../_catalogs/masterpage/#\"><span style=\"padding: 7p" +
                        "x; width: 16px; height: 16px; overflow: hidden; display: inline-block;\"><span cl" +
                        "ass=\"s4-clust\" style=\"width: 16px; height: 16px; overflow: hidden; display: inli" +
                        "ne-block; position: relative;\"><img style=\"border: 0px currentColor; left: -19px" +
                        "; top: -1px; position: absolute;\" alt=\"Справка\" src=\"/_layouts/15/1049/images/sp" +
                        "intl.png?rev=23\"></span></span></a>\r\n</span>\r\n\t\t\t\t</div>\r\n                    <d" +
                        "iv class=\"lk-box\">\r\n                        <div class=\"img\">\r\n                 " +
                        "           <img src=\"img/face.png\" alt=\"\"></div>\r\n                        <div c" +
                        "lass=\"tt\">\r\n                            <div class=\"hi\">Здравствуйте</div>\r\n    " +
                        "                        <div class=\"name\"><a title=\"Открыть меню\" class=\"ms-core" +
                        "-menu-root\" id=\"zz4_Menu\" accesskey=\"/\" onkeydown=\"MMU_EcbLinkOnKeyDown(byid(\'zz" +
                        "1_ID_PersonalActionMenu\'), MMU_GetMenuFromClientId(\'zz4_Menu\'), event);\" onclick" +
                        "=\" CoreInvoke(\'MMU_Open\',byid(\'zz1_ID_PersonalActionMenu\'), MMU_GetMenuFromClien" +
                        "tId(\'zz4_Menu\'),event,true, null, 0); return false;\" onfocus=\"MMU_EcbLinkOnFocus" +
                        "Blur(byid(\'zz1_ID_PersonalActionMenu\'), this, true);\" oncontextmenu=\"ClkElmt(thi" +
                        "s); return false;\" href=\"javascript:;\" serverclientid=\"zz4_Menu\" menutokenvalues" +
                        "=\"MENUCLIENTID=zz4_Menu,TEMPLATECLIENTID=zz1_ID_PersonalActionMenu\">Валентин Кри" +
                        "тенко<span class=\"ms-accessible\">Для открытия меню воспользуйтесь сочетанием кла" +
                        "виш SHIFT+ВВОД (в новом окне).</span></a></div>\r\n                        \r\n     " +
                        "                   </div>\r\n                        <div class=\"drop-list\">\r\n    " +
                        "                        <ul>\r\n                                <li><a href=\"\">Изм" +
                        "енить</a></li>\r\n                                <li><a href=\"\">Выйти</a></li>\r\n " +
                        "                           </ul>\r\n                        </div>\r\n              " +
                        "      </div>\r\n                </div>\r\n                <div class=\"toggle_mnu\">\r\n" +
                        "                    <span class=\"sandwich\">\r\n                        <span class" +
                        "=\"sw-topper\"></span>\r\n                        <span class=\"sw-bottom\"></span>\r\n " +
                        "                       <span class=\"sw-footer\"></span>\r\n                    </sp" +
                        "an>\r\n                </div>\r\n                <ul class=\"nav\">\r\n                 " +
                        "   <li><a href=\"\">Новости</a></li>\r\n                    <li><a href=\"\">Льготы</a" +
                        "></li>\r\n                    <li><a href=\"\">Сервисы и документы</a></li>\r\n       " +
                        "             <li><a href=\"\">Карьера</a></li>\r\n                    <li><a href=\"\"" +
                        ">Наша жизнь</a></li>\r\n                    <li><a href=\"\">Справочник</a></li>\r\n  " +
                        "                  <li><a href=\"\">Компания</a></li>\r\n                </ul>\r\n     " +
                        "       </div>\r\n        </div>\r\n        <div class=\"main bg-white\">\r\n            " +
                        "<div class=\"toping-box\">\r\n                <div class=\"container\">\r\n             " +
                        "       <ul class=\"pagin\">\r\n                        <li><a href=\"\">Главная</a></l" +
                        "i>\r\n                    </ul>\r\n                    <div class=\"title\">Редактиров" +
                        "ание объявления</div>\r\n                </div>\r\n            </div>\r\n            <" +
                        "div class=\"container\">\r\n                <div class=\"two-columns\">\r\n             " +
                        "       <div class=\"row\">\r\n                        <div class=\"col-md-9 col-sm-12" +
                        "\">\r\n                            <div class=\"content-box\">\r\n\r\n                   " +
                        "             <div class=\"section-padding\">\r\n                                    " +
                        "<form action=\"\" class=\"default-form edit-form\">\r\n                               " +
                        "         <div class=\"row-inp\">\r\n                                            <p c" +
                        "lass=\"label\">Заголовок</p>\r\n                                            <input t" +
                        "ype=\"text\">\r\n                                        </div>\r\n                   " +
                        "                     <div class=\"row-inp\">\r\n                                    " +
                        "        <p class=\"label\">Категории</p>\r\n                                        " +
                        "    <select class=\"cat-select\">\r\n                                               " +
                        " <option value=\"\"></option>\r\n                                                <op" +
                        "tion value=\"\">Категории</option>\r\n                                            </" +
                        "select>\r\n                                        </div>\r\n                       " +
                        "                 <div class=\"row-inp\">\r\n                                        " +
                        "    <p class=\"label\">Описание</p>\r\n                                            <" +
                        "textarea></textarea>\r\n                                        </div>\r\n          " +
                        "                              <div class=\"row-inp\">\r\n                           " +
                        "                 <p class=\"label\">Фотографии, не более 3</p>\r\n                  " +
                        "                          <div class=\"file\">\r\n                                  " +
                        "              <input id=\"file4\" type=\"file\" title=\"Загрузите фото\" />\r\n         " +
                        "                                       <span class=\"file-input-text\">name.png</s" +
                        "pan>\r\n                                            </div>\r\n                      " +
                        "                  </div>\r\n                                        <div class=\"ro" +
                        "w-inp\">\r\n                                            <p class=\"label\">Объявление" +
                        " будет отправлено на модерацию</p>\r\n                                            " +
                        "<input type=\"submit\" class=\"btn\" value=\"Сохранить\">\r\n                           " +
                        "             </div>\r\n                                    </form>\r\n              " +
                        "                  </div>\r\n\r\n                            </div>\r\n                " +
                        "        </div>\r\n                        <div class=\"col-md-3 col-sm-12\">\r\n      " +
                        "                      <div class=\"aside aside-moved-top\">\r\n                     " +
                        "           <div class=\"aside-box news-archive\">\r\n                               " +
                        "     <div class=\"aside-title title\">Объявление опубликовано</div>\r\n             " +
                        "                       <ul class=\"month-list\">\r\n                                " +
                        "        <li><a href=\"\">В архив</a></li>\r\n                                       " +
                        " <li><a href=\"\">Удалить</a></li>\r\n                                    </ul>\r\n   " +
                        "                             </div>\r\n                            </div>\r\n       " +
                        "                 </div>\r\n                    </div>\r\n                </div>\r\n   " +
                        "         </div>\r\n        </div>\r\n        <div class=\"footer footer-inner\">\r\n    " +
                        "        <div class=\"container\">\r\n                <div class=\"row\">\r\n            " +
                        "        <div class=\"col-sm-12\">\r\n                        <div class=\"wrap\">\r\n   " +
                        "                         <div class=\"copy\">© 2018 РН Банк. Корпоративный портал " +
                        "сотрудников банка.</div>\r\n                        </div>\r\n                    </" +
                        "div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n" +
                        "\r\n    <!--[if lt IE 9]>\r\n\t<script src=\"libs/html5shiv/es5-shim.min.js\"></script>" +
                        "\r\n\t<script src=\"libs/html5shiv/html5shiv.min.js\"></script>\r\n\t<script src=\"libs/h" +
                        "tml5shiv/html5shiv-printshiv.min.js\"></script>\r\n\t<script src=\"libs/respond/respo" +
                        "nd.min.js\"></script>\r\n\t<![endif]-->\r\n\r\n    <script src=\"http://sp-sql/sites/Home" +
                        "/Verstka/libs/jquery/jquery-1.11.2.min.js\"></script>\r\n    <script src=\"http://sp" +
                        "-sql/sites/Home/Verstka/libs/plugins-scroll/plugins-scroll.js\"></script>\r\n    <s" +
                        "cript src=\"http://sp-sql/sites/Home/Verstka/js/owl.carousel.js\"></script>\r\n    <" +
                        "script src=\"http://sp-sql/sites/Home/Verstka/js/jcf.js\"></script>\r\n    <script s" +
                        "rc=\"http://sp-sql/sites/Home/Verstka/js/jcf.checkbox.js\"></script>\r\n    <script " +
                        "src=\"http://sp-sql/sites/Home/Verstka/js/jcf.radio.js\"></script>\r\n    <script sr" +
                        "c=\"http://sp-sql/sites/Home/Verstka/js/common.js\"></script>\r\n\r\n</body>\r\n</html>\r" +
                        "\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
