//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUI.Edit_admin {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class Edit_admin {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(Edit_admin target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::SHPUI.Edit_admin.Edit_admin @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html class=\"ie ie6\" lang=\"en\"> <![endif]-->" +
                        "\r\n<!--[if IE 7 ]><html class=\"ie ie7\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 8 ]><h" +
                        "tml class=\"ie ie8\" lang=\"en\"> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!--><html" +
                        " lang=\"ru\"> <!--<![endif]-->\r\n\r\n<head>\r\n\t<meta charset=\"utf-8\">\r\n\t<title>Заголов" +
                        "ок</title>\r\n\t<meta name=\"description\" content=\"\">\r\n\r\n\t<meta http-equiv=\"X-UA-Com" +
                        "patible\" content=\"IE=edge\">\r\n\t<meta name=\"viewport\" content=\"width=device-width," +
                        " initial-scale=1, maximum-scale=1\">\r\n\t\r\n\t<link rel=\"stylesheet\" href=\"http://sp-" +
                        "sql/sites/Home/Verstka/css/owl.carousel.min.css\">\r\n\t<link rel=\"stylesheet\" href=" +
                        "\"http://sp-sql/sites/Home/Verstka/css/owl.theme.default.min.css\">\r\n\r\n\t<link rel=" +
                        "\"stylesheet\" href=\"http://sp-sql/sites/Home/Verstka/libs/bootstrap/css/bootstrap" +
                        "-grid.min.css\">\r\n\t<link href=\"https://fonts.googleapis.com/css?family=Roboto:300" +
                        ",400,500,700,900&amp;subset=cyrillic,cyrillic-ext\" rel=\"stylesheet\">\r\n\t<link rel" +
                        "=\"stylesheet\" href=\"http://sp-sql/sites/Home/Verstka/css/main.css\">\r\n\t<link rel=" +
                        "\"stylesheet\" href=\"http://sp-sql/sites/Home/Verstka/css/media.css\">\r\n\r\n</head>\r\n" +
                        "\r\n<body>\r\n<div id=\"wrapper\">\r\n\t<div class=\"header\">\r\n\t\t<div class=\"container\">\r\n" +
                        "\t\t\t<div class=\"top-line\">\r\n\t\t\t\t<div class=\"logo\"><a href=\"\"><img src=\"http://sp-" +
                        "sql/sites/Home/Verstka/img/logo.svg\" alt=\"\"></a></div>\r\n\t\t\t\t<form action=\"\" clas" +
                        "s=\"search-form\">\r\n\t\t\t\t\t<input type=\"text\" placeholder=\"Поиск\">\r\n\t\t\t\t\t<input type" +
                        "=\"submit\" value=\"\">\r\n\t\t\t\t</form>\r\n\t\t\t\t<div class=\"lk-box\">\r\n\t\t\t\t\t<div class=\"img" +
                        "\"><img src=\"http://sp-sql/sites/Home/Verstka/img/face.png\" alt=\"\"></div>\r\n\t\t\t\t\t<" +
                        "div class=\"tt\">\r\n\t\t\t\t\t\t<div class=\"hi\">Здравствуйте</div>\r\n\t\t\t\t\t\t<div class=\"nam" +
                        "e\">Виктория Николаевна</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div class=\"drop-list\">\r\n\t\t\t\t\t\t<" +
                        "ul>\r\n\t\t\t\t\t\t\t<li><a href=\"\">Изменить</a></li>\r\n\t\t\t\t\t\t\t<li><a href=\"\">Выйти</a></l" +
                        "i>\r\n\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t\t<div class=\"toggle_mnu\">" +
                        "\r\n\t\t\t\t<span class=\"sandwich\">\r\n\t\t\t\t<span class=\"sw-topper\"></span>\r\n\t\t\t\t<span cl" +
                        "ass=\"sw-bottom\"></span>\r\n\t\t\t\t<span class=\"sw-footer\"></span>\r\n\t\t\t\t</span>\r\n\t\t\t</" +
                        "div>\r\n\t\t\t<ul class=\"nav\">\r\n\t\t\t\t<li><a href=\"\">Новости</a></li>\r\n\t\t\t\t<li><a href=" +
                        "\"\">Льготы</a></li>\r\n\t\t\t\t<li><a href=\"\">Сервисы и документы</a></li>\r\n\t\t\t\t<li><a " +
                        "href=\"\">Карьера</a></li>\r\n\t\t\t\t<li><a href=\"\">Наша жизнь</a></li>\r\n\t\t\t\t<li><a hre" +
                        "f=\"\">Справочник</a></li>\r\n\t\t\t\t<li><a href=\"\">Компания</a></li>\r\n\t\t\t</ul>\r\n\t\t</di" +
                        "v>\r\n\t</div>\r\n\t<div class=\"main bg-white\">\r\n\t\t<div class=\"toping-box\">\r\n\t\t\t<div c" +
                        "lass=\"container\">\r\n\t\t\t\t<ul class=\"pagin\">\r\n\t\t\t\t\t<li><a href=\"\">Главная</a></li>\r" +
                        "\n\t\t\t\t</ul>\r\n\t\t\t\t<div class=\"title\">Редактирование объявления</div>\r\n\t\t\t</div>\r\n\t" +
                        "\t</div>\r\n\t\t<div class=\"container\">\r\n\t\t\t<div class=\"two-columns\">\r\n\t\t\t\t<div class" +
                        "=\"row\">\r\n\t\t\t\t\t<div class=\"col-md-9 col-sm-12\">\r\n\t\t\t\t\t\t<div class=\"content-box\">\r" +
                        "\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"section-padding\">\r\n\t\t\t\t\t\t\t\t<form action=\"\" class=\"d" +
                        "efault-form edit-form\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"lab" +
                        "el\">Заголовок</p>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div" +
                        " class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"label\">Категории</p>\r\n\t\t\t\t\t\t\t\t\t\t<select c" +
                        "lass=\"cat-select\">\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"\"></option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option va" +
                        "lue=\"\">Категории</option>\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div c" +
                        "lass=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"label\">Описание</p>\r\n\t\t\t\t\t\t\t\t\t\t<textarea></" +
                        "textarea>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"" +
                        "label\">Фотографии, не более 3</p>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"file\">\r\n\t\t\t\t\t\t\t\t\t\t\t<inp" +
                        "ut id=\"file4\" type=\"file\" title=\"Загрузите фото\" />\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"fil" +
                        "e-input-text\">name.png</span>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div " +
                        "class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<ul class=\"download-images\">\r\n\t\t\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t" +
                        "\t\t\t\t\t\t\t<img src=\"http://sp-sql/sites/Home/Verstka/img/2.png\" alt=\"\">\r\n\t\t\t\t\t\t\t\t\t\t" +
                        "\t\t<span class=\"delete\"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<" +
                        "img src=\"http://sp-sql/sites/Home/Verstka/img/2.png\" alt=\"\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<span " +
                        "class=\"delete\"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t" +
                        "\t\t\t\t\t<div class=\"row-inp\">\r\n\t\t\t\t\t\t\t\t\t\t<p class=\"label\">Объявление будет отправле" +
                        "но на модерацию</p>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn\" value=\"Сохранить" +
                        "\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t</form>\r\n\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>" +
                        "\r\n\t\t\t\t\t<div class=\"col-md-3 col-sm-12\">\r\n\t\t\t\t\t\t<div class=\"aside aside-moved-top" +
                        "\">\r\n\t\t\t\t\t\t\t<div class=\"aside-box news-archive\">\r\n\t\t\t\t\t\t\t\t<div class=\"aside-title" +
                        " title\">Объявление на модерации</div>\r\n\t\t\t\t\t\t\t\t<a href=\"\" class=\"btn\">Опубликова" +
                        "ть</a>\r\n\t\t\t\t\t\t\t\t<ul class=\"month-list\">\r\n\t\t\t\t\t\t\t\t\t<li><a href=\"\">Редактировать</" +
                        "a></li>\r\n\t\t\t\t\t\t\t\t\t<li><a href=\"\">В архив</a></li>\r\n\t\t\t\t\t\t\t\t\t<li><a href=\"\">Удали" +
                        "ть</a></li>\r\n\t\t\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>" +
                        "\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class=\"footer footer-inner\">\r\n\t\t<div class" +
                        "=\"container\">\r\n\t\t\t<div class=\"row\">\r\n\t\t\t\t<div class=\"col-sm-12\">\r\n\t\t\t\t\t<div clas" +
                        "s=\"wrap\">\r\n\t\t\t\t\t\t<div class=\"copy\">© 2018 РН Банк. Корпоративный портал сотрудни" +
                        "ков банка.</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r" +
                        "\n\r\n\r\n\t<!--[if lt IE 9]>\r\n\t<script src=\"libs/html5shiv/es5-shim.min.js\"></script>" +
                        "\r\n\t<script src=\"libs/html5shiv/html5shiv.min.js\"></script>\r\n\t<script src=\"libs/h" +
                        "tml5shiv/html5shiv-printshiv.min.js\"></script>\r\n\t<script src=\"libs/respond/respo" +
                        "nd.min.js\"></script>\r\n\t<![endif]-->\r\n\r\n\t<script src=\"http://sp-sql/sites/Home/Ve" +
                        "rstka/libs/jquery/jquery-1.11.2.min.js\"></script>\r\n\t<script src=\"http://sp-sql/s" +
                        "ites/Home/Verstka/libs/plugins-scroll/plugins-scroll.js\"></script>\r\n\t<script src" +
                        "=\"http://sp-sql/sites/Home/Verstka/js/owl.carousel.js\"></script>\r\n\t<script src=\"" +
                        "http://sp-sql/sites/Home/Verstka/js/jcf.js\"></script>\r\n\t<script src=\"http://sp-s" +
                        "ql/sites/Home/Verstka/js/jcf.checkbox.js\"></script>\r\n\t<script src=\"http://sp-sql" +
                        "/sites/Home/Verstka/js/jcf.radio.js\"></script>\r\n\t<script src=\"http://sp-sql/site" +
                        "s/Home/Verstka/js/common.js\"></script>\r\n\t\r\n</body>\r\n</html>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
