//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUI.CreateEditBulletinBoard {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class CreateEditBulletinBoard {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(CreateEditBulletinBoard target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::SHPUI.CreateEditBulletinBoard.CreateEditBulletinBoard @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html class=\"ie ie6\" lang=\"en\"> <![endif]-->" +
                        "\r\n<!--[if IE 7 ]><html class=\"ie ie7\" lang=\"en\"> <![endif]-->\r\n<!--[if IE 8 ]><h" +
                        "tml class=\"ie ie8\" lang=\"en\"> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!-->\r\n<ht" +
                        "ml lang=\"ru\">\r\n<!--<![endif]-->\r\n\r\n<head>\r\n    <meta charset=\"utf-8\">\r\n    <titl" +
                        "e>Заголовок</title>\r\n    <meta name=\"description\" content=\"\">\r\n\r\n    <meta http-" +
                        "equiv=\"X-UA-Compatible\" content=\"IE=edge;chrome=1\" />\r\n    <meta name=\"viewport\"" +
                        " content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n\r\n    <script " +
                        "src=\"http://sp-sql/sites/Home/Verstka/libs/jquery/jquery-1.11.2.min.js\"></script" +
                        "> \r\n    <link rel=\"stylesheet\" href=\"http://sp-sql/sites/Home/Verstka/css/owl.th" +
                        "eme.default.min.css\">\r\n\r\n    <link rel=\"stylesheet\" href=\"http://sp-sql/sites/Ho" +
                        "me/Verstka/libs/bootstrap/css/bootstrap-grid.min.css\">\r\n    <link href=\"https://" +
                        "fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&amp;subset=cyrillic,c" +
                        "yrillic-ext\" rel=\"stylesheet\">\r\n    <link rel=\"stylesheet\" href=\"http://sp-sql/s" +
                        "ites/Home/Verstka/css/main.css\">\r\n    <link rel=\"stylesheet\" href=\"http://sp-sql" +
                        "/sites/Home/Verstka/css/media.css\">\r\n   \r\n    <script src=\"http://sp-sql/sites/H" +
                        "ome/Verstka/Layouts/SHPUI/JS/EditBilboard/RightPanel/BoardingModeration.js\"></sc" +
                        "ript>\r\n</head>\r\n\r\n<body>\r\n    <div id=\"wrapper\">\r\n        <div class=\"header\">\r\n" +
                        "            <div class=\"container\">\r\n                <div class=\"top-line\">\r\n   " +
                        "                 <div class=\"logo\"><a href=\"\">\r\n                        <img src" +
                        "=\"img/logo.svg\" alt=\"\"></a></div>\r\n                    <form action=\"\" class=\"se" +
                        "arch-form\">\r\n                        <input type=\"text\" placeholder=\"Поиск\">\r\n  " +
                        "                      <input type=\"submit\" value=\"\">\r\n                    </form" +
                        ">\r\n                    <div id=\"suiteBarButtons\">\r\n\t\t\t\t\t   <span class=\"ms-sitea" +
                        "ctions-root\" id=\"siteactiontd\">\r\n\t\t\t\t\t   \r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<span style=\"display: n" +
                        "one;\"><menu id=\"zz5_SiteActionsMenuMain\" type=\"ServerMenu\" hideicons=\"true\"><ie:" +
                        "menuitem id=\"zz6_MenuItem_ShareThisSite\" type=\"option\" menugroupid=\"100\" descrip" +
                        "tion=\"Посмотреть, кто здесь находится, и пригласить новых участников.\" text=\"Сов" +
                        "местно с...\" onmenuclick=\"EnsureScriptFunc(\'sharing.js\', \'DisplaySharedWithDialo" +
                        "g\', function () { DisplaySharedWithDialog(\'\\u002fsites\\u002fHome\\u002f\'); })\" ch" +
                        "ecked=\"false\" enabled=\"true\" onMenuClick_Original=\"EnsureScriptFunc(\'sharing.js\'" +
                        ", \'DisplaySharedWithDialog\', function () { DisplaySharedWithDialog(\'\\u002fsites\\" +
                        "u002fHome\\u002f\'); })\" text_Original=\"Совместно с...\" description_Original=\"Посм" +
                        "отреть, кто здесь находится, и пригласить новых участников.\" valOrig=\"&#10;&#9;\"" +
                        "></ie:menuitem>\r\n\t<ie:menuitem id=\"ctl00_SiteActionsMenuMain_ctl00_MenuItem_Edit" +
                        "Page\" type=\"option\" menugroupid=\"200\" description=\"Изменение контента этой стран" +
                        "ицы.\" text=\"Изменение страницы\" onmenuclick=\"window.location = \'javascript:{Ensu" +
                        "reScriptParams(\\\'ribbon\\\', \\\'ChangeWikiPageMode\\\', true);}\';\" iconsrc=\"/_layouts" +
                        "/15/images/ActionsEditPage.png?rev=23\" checked=\"false\" enabled=\"true\" onMenuClic" +
                        "k_Original=\"window.location = \'javascript:{EnsureScriptParams(\\\'ribbon\\\', \\\'Chan" +
                        "geWikiPageMode\\\', true);}\';\" text_Original=\"Изменение страницы\" description_Orig" +
                        "inal=\"Изменение контента этой страницы.\" valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<i" +
                        "e:menuitem id=\"zz7_MenuItem_CreatePage\" type=\"option\" menugroupid=\"200\" descript" +
                        "ion=\"Создание страницы, которую можно настроить.\" text=\"Добавление страницы\" onm" +
                        "enuclick=\"OpenCreateWebPageDialog(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u" +
                        "002fcreatewebpage.aspx\')\" iconsrc=\"/_layouts/15/images/NewContentPageHH.png?rev=" +
                        "23\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"OpenCreateWebPageDialog" +
                        "(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u002fcreatewebpage.aspx\')\" text_Or" +
                        "iginal=\"Добавление страницы\" description_Original=\"Создание страницы, которую мо" +
                        "жно настроить.\" valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz8_MenuIt" +
                        "em_Create\" type=\"option\" menugroupid=\"200\" description=\"Создание других типов ст" +
                        "раниц, списков, библиотек и сайтов.\" text=\"Добавить приложение\" onmenuclick=\"GoT" +
                        "oPage(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u002faddanapp.aspx\')\" checked" +
                        "=\"false\" enabled=\"true\" onMenuClick_Original=\"GoToPage(\'\\u002fsites\\u002fHome\\u0" +
                        "02f_layouts\\u002f15\\u002faddanapp.aspx\')\" text_Original=\"Добавить приложение\" de" +
                        "scription_Original=\"Создание других типов страниц, списков, библиотек и сайтов.\"" +
                        " valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz9_MenuItem_ViewAllSiteC" +
                        "ontents\" type=\"option\" menugroupid=\"200\" description=\"Просмотр всех библиотек и " +
                        "списков на данном сайте.\" text=\"Контент сайта\" onmenuclick=\"STSNavigate2(event,\'" +
                        "/sites/Home/_layouts/15/viewlsts.aspx\');\" iconsrc=\"/_layouts/15/images/allconten" +
                        "t32.png?rev=23\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"STSNavigate" +
                        "2(event,\'/sites/Home/_layouts/15/viewlsts.aspx\');\" text_Original=\"Контент сайта\"" +
                        " description_Original=\"Просмотр всех библиотек и списков на данном сайте.\" valOr" +
                        "ig=\"&#10;&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz10_MenuItem_ChangeTheLook\" ty" +
                        "pe=\"option\" menugroupid=\"300\" description=\"Измените внешний вид сайта\" text=\"Изм" +
                        "енение оформления\" onmenuclick=\"STSNavigate2(event,\'/sites/Home/_layouts/15/desi" +
                        "gngallery.aspx\');\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"STSNavig" +
                        "ate2(event,\'/sites/Home/_layouts/15/designgallery.aspx\');\" text_Original=\"Измене" +
                        "ние оформления\" description_Original=\"Измените внешний вид сайта\" valOrig=\"&#10;" +
                        "&#9;\"></ie:menuitem>\r\n\t<ie:menuitem id=\"zz11_MenuItem_Settings\" type=\"option\" me" +
                        "nugroupid=\"300\" description=\"Доступ ко всем параметрам этого сайта.\" text=\"Парам" +
                        "етры сайта\" onmenuclick=\"GoToPage(\'\\u002fsites\\u002fHome\\u002f_layouts\\u002f15\\u" +
                        "002fsettings.aspx\')\" iconsrc=\"/_layouts/15/images/settingsIcon.png?rev=23\" check" +
                        "ed=\"false\" enabled=\"true\" onMenuClick_Original=\"GoToPage(\'\\u002fsites\\u002fHome\\" +
                        "u002f_layouts\\u002f15\\u002fsettings.aspx\')\" text_Original=\"Параметры сайта\" desc" +
                        "ription_Original=\"Доступ ко всем параметрам этого сайта.\" valOrig=\"&#10;&#9;\"></" +
                        "ie:menuitem>\r\n\t<ie:menuitem id=\"ctl00_SiteActionsMenuMain_ctl00_ctl02\" type=\"opt" +
                        "ion\" menugroupid=\"2147483647\" description=\"Начало работы с сайтом.\" text=\"Присту" +
                        "пая к работе\" onmenuclick=\"STSNavigate2(event,\'/sites/Home/GettingStarted.aspx\')" +
                        ";\" checked=\"false\" enabled=\"true\" onMenuClick_Original=\"STSNavigate2(event,\'/sit" +
                        "es/Home/GettingStarted.aspx\');\" text_Original=\"Приступая к работе\" description_O" +
                        "riginal=\"Начало работы с сайтом.\" valOrig=\"&#10;&#9;\"></ie:menuitem>\r\n\t</menu></" +
                        "span><span title=\"Параметры\" class=\"ms-siteactions-normal\" id=\"zz12_SiteActionsM" +
                        "enu_t\" onmouseover=\"MMU_PopMenuIfShowing(this);MMU_EcbTableMouseOverOut(this, tr" +
                        "ue)\" onclick=\" CoreInvoke(\'MMU_Open\',byid(\'zz5_SiteActionsMenuMain\'), MMU_GetMen" +
                        "uFromClientId(\'zz12_SiteActionsMenu\'),event,true, null, 0); return false;\" oncon" +
                        "textmenu=\"ClkElmt(this); return false;\" foa=\"MMU_GetMenuFromClientId(\'zz12_SiteA" +
                        "ctionsMenu\')\" hoverinactive=\"ms-siteactions-normal\" hoveractive=\"ms-siteactions-" +
                        "normal ms-siteactions-hover\"><a title=\"Параметры\" class=\"ms-core-menu-root\" id=\"" +
                        "zz12_SiteActionsMenu\" accesskey=\"/\" onkeydown=\"MMU_EcbLinkOnKeyDown(byid(\'zz5_Si" +
                        "teActionsMenuMain\'), MMU_GetMenuFromClientId(\'zz12_SiteActionsMenu\'));\" href=\"ja" +
                        "vascript:;\" serverclientid=\"zz12_SiteActionsMenu\" menutokenvalues=\"MENUCLIENTID=" +
                        "zz12_SiteActionsMenu,TEMPLATECLIENTID=zz5_SiteActionsMenuMain\"><span class=\"ms-s" +
                        "iteactions-imgspan\"><img title=\"Параметры\" class=\"ms-core-menu-buttonIcon\" alt=\"" +
                        "Параметры\" src=\"/_layouts/15/images/spcommon.png?rev=23\"></span><span class=\"ms-" +
                        "accessible\">Для открытия меню воспользуйтесь сочетанием клавиш SHIFT+ВВОД (в нов" +
                        "ом окне).</span></a></span></span>\r\n<span id=\"ms-help\">\r\n\t<a title=\"Справка\" id=" +
                        "\"ctl00_TopHelpLink\" accesskey=\"6\" style=\"width: 30px; height: 30px; display: inl" +
                        "ine-block;\" onmouseover=\"this.firstChild.firstChild.firstChild.style.left=\'-1px\'" +
                        "; this.firstChild.firstChild.firstChild.style.top=\'-1px\';\" onmouseout=\"this.firs" +
                        "tChild.firstChild.firstChild.style.left=\'-19px\'; this.firstChild.firstChild.firs" +
                        "tChild.style.top=\'-1px\';\" onclick=\"TopHelpButtonClick(\'HelpHome\',event);return f" +
                        "alse\" href=\"../_catalogs/masterpage/#\"><span style=\"padding: 7px; width: 16px; h" +
                        "eight: 16px; overflow: hidden; display: inline-block;\"><span class=\"s4-clust\" st" +
                        "yle=\"width: 16px; height: 16px; overflow: hidden; display: inline-block; positio" +
                        "n: relative;\"><img style=\"border: 0px currentColor; left: -19px; top: -1px; posi" +
                        "tion: absolute;\" alt=\"Справка\" src=\"/_layouts/15/1049/images/spintl.png?rev=23\">" +
                        "</span></span></a>\r\n</span>\r\n\t\t\t\t</div>\r\n                    <div class=\"lk-box\"" +
                        ">\r\n                        <div class=\"img\">\r\n                            <img s" +
                        "rc=\"img/face.png\" alt=\"\"></div>\r\n                        <div class=\"tt\">\r\n     " +
                        "                       <div class=\"hi\">Здравствуйте</div>\r\n                     " +
                        "       <div class=\"name\"><a title=\"Открыть меню\" class=\"ms-core-menu-root\" id=\"z" +
                        "z4_Menu\" accesskey=\"/\" onkeydown=\"MMU_EcbLinkOnKeyDown(byid(\'zz1_ID_PersonalActi" +
                        "onMenu\'), MMU_GetMenuFromClientId(\'zz4_Menu\'), event);\" onclick=\" CoreInvoke(\'MM" +
                        "U_Open\',byid(\'zz1_ID_PersonalActionMenu\'), MMU_GetMenuFromClientId(\'zz4_Menu\'),e" +
                        "vent,true, null, 0); return false;\" onfocus=\"MMU_EcbLinkOnFocusBlur(byid(\'zz1_ID" +
                        "_PersonalActionMenu\'), this, true);\" oncontextmenu=\"ClkElmt(this); return false;" +
                        "\" href=\"javascript:;\" serverclientid=\"zz4_Menu\" menutokenvalues=\"MENUCLIENTID=zz" +
                        "4_Menu,TEMPLATECLIENTID=zz1_ID_PersonalActionMenu\">Валентин Критенко<span class=" +
                        "\"ms-accessible\">Для открытия меню воспользуйтесь сочетанием клавиш SHIFT+ВВОД (в" +
                        " новом окне).</span></a></div>\r\n                        \r\n                      " +
                        "  </div>\r\n                        <div class=\"drop-list\">\r\n                     " +
                        "       <ul>\r\n                                <li><a href=\"\">Изменить</a></li>\r\n " +
                        "                               <li><a href=\"\">Выйти</a></li>\r\n                  " +
                        "          </ul>\r\n                        </div>\r\n                    </div>\r\n   " +
                        "             </div>\r\n                <div class=\"toggle_mnu\">\r\n                 " +
                        "   <span class=\"sandwich\">\r\n                        <span class=\"sw-topper\"></sp" +
                        "an>\r\n                        <span class=\"sw-bottom\"></span>\r\n                  " +
                        "      <span class=\"sw-footer\"></span>\r\n                    </span>\r\n            " +
                        "    </div>\r\n                <ul class=\"nav\">\r\n                    <li><a href=\"\"" +
                        ">Новости</a></li>\r\n                    <li><a href=\"\">Льготы</a></li>\r\n         " +
                        "           <li><a href=\"\">Сервисы и документы</a></li>\r\n                    <li>" +
                        "<a href=\"\">Карьера</a></li>\r\n                    <li><a href=\"\">Наша жизнь</a></" +
                        "li>\r\n                    <li><a href=\"\">Справочник</a></li>\r\n                   " +
                        " <li><a href=\"\">Компания</a></li>\r\n                </ul>\r\n            </div>\r\n  " +
                        "      </div>\r\n        <div class=\"main bg-white\">\r\n            <div class=\"topin" +
                        "g-box\">\r\n                <div class=\"container\">\r\n                    <ul class=" +
                        "\"pagin\">\r\n                        <li><a href=\"\">Главная</a></li>\r\n             " +
                        "       </ul>\r\n                    <div class=\"title\">Редактирование объявления</" +
                        "div>\r\n                </div>\r\n            </div>\r\n            <div class=\"contai" +
                        "ner\">\r\n                <div class=\"two-columns\">\r\n                    <div class" +
                        "=\"row\" id =\"RightPanel\">\r\n                        <div class=\"col-md-9 col-sm-12" +
                        "\">\r\n                            <div class=\"content-box\">\r\n\r\n                   " +
                        "             <div class=\"section-padding\">\r\n                                    " +
                        "<form action=\"\" class=\"default-form edit-form\">\r\n                               " +
                        "         <div class=\"row-inp\">\r\n                                            <p c" +
                        "lass=\"label\">Заголовок</p>\r\n                                            <input t" +
                        "ype=\"text\">\r\n                                        </div>\r\n                   " +
                        "                     <div class=\"row-inp\">\r\n                                    " +
                        "        <p class=\"label\">Категории</p>\r\n                                        " +
                        "    <select class=\"cat-select\">\r\n                                               " +
                        " <option value=\"\"></option>\r\n                                                <op" +
                        "tion value=\"\">Категории</option>\r\n                                            </" +
                        "select>\r\n                                        </div>\r\n                       " +
                        "                 <div class=\"row-inp\">\r\n                                        " +
                        "    <p class=\"label\">Описание</p>\r\n                                            <" +
                        "textarea></textarea>\r\n                                        </div>\r\n          " +
                        "                              <div class=\"row-inp\">\r\n                           " +
                        "                 <p class=\"label\">Фотографии, не более 3</p>\r\n                  " +
                        "                          <div class=\"file\">\r\n                                  " +
                        "              <input id=\"file4\" type=\"file\" title=\"Загрузите фото\" />\r\n         " +
                        "                                       <span class=\"file-input-text\">name.png</s" +
                        "pan>\r\n                                            </div>\r\n                      " +
                        "                  </div>\r\n                                        <div class=\"ro" +
                        "w-inp\">\r\n                                            <p class=\"label\">Объявление" +
                        " будет отправлено на модерацию</p>\r\n                                            " +
                        "<input type=\"submit\" class=\"btn\" value=\"Сохранить\">\r\n                           " +
                        "             </div>\r\n                                    </form>\r\n              " +
                        "                  </div>\r\n\r\n                            </div>\r\n                " +
                        "        </div>\r\n                    </div>\r\n                </div>\r\n            " +
                        "</div>\r\n        </div>\r\n        <div class=\"footer footer-inner\">\r\n            <" +
                        "div class=\"container\">\r\n                <div class=\"row\">\r\n                    <" +
                        "div class=\"col-sm-12\">\r\n                        <div class=\"wrap\">\r\n            " +
                        "                <div class=\"copy\">© 2018 РН Банк. Корпоративный портал сотрудник" +
                        "ов банка.</div>\r\n                        </div>\r\n                    </div>\r\n   " +
                        "             </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n\r\n    <!-" +
                        "-[if lt IE 9]>\r\n\t<script src=\"libs/html5shiv/es5-shim.min.js\"></script>\r\n\t<scrip" +
                        "t src=\"libs/html5shiv/html5shiv.min.js\"></script>\r\n\t<script src=\"libs/html5shiv/" +
                        "html5shiv-printshiv.min.js\"></script>\r\n\t<script src=\"libs/respond/respond.min.js" +
                        "\"></script>\r\n\t<![endif]-->\r\n\r\n    <script src=\"http://sp-sql/sites/Home/Verstka/" +
                        "libs/jquery/jquery-1.11.2.min.js\"></script>\r\n    <!-- \r\n    <script src=\"http://" +
                        "sp-sql/sites/Home/Verstka/libs/plugins-scroll/plugins-scroll.js\"></script>\r\n    " +
                        "-->\r\n    <script src=\"http://sp-sql/sites/Home/Verstka/js/jcf.js\"></script>\r\n   " +
                        " <script src=\"http://sp-sql/sites/Home/Verstka/js/jcf.checkbox.js\"></script>\r\n  " +
                        "  <script src=\"http://sp-sql/sites/Home/Verstka/js/jcf.radio.js\"></script>\r\n    " +
                        "<script src=\"http://sp-sql/sites/Home/Verstka/js/common.js\"></script>\r\n\r\n</body>" +
                        "\r\n</html>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
